# Generated by Django 5.1 on 2024-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_score1_match_score2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
