# Generated by Django 5.1 on 2024-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_play',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
