# Generated by Django 5.1 on 2024-08-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_first_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score2',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game1_score1', models.PositiveIntegerField(default=0)),
                ('game1_score2', models.PositiveIntegerField(default=0)),
                ('game2_score1', models.PositiveIntegerField(default=0)),
                ('game2_score2', models.PositiveIntegerField(default=0)),
                ('game3_score1', models.PositiveIntegerField(default=0)),
                ('game3_score2', models.PositiveIntegerField(default=0)),
                ('game4_score1', models.PositiveIntegerField(default=0)),
                ('game4_score2', models.PositiveIntegerField(default=0)),
                ('game5_score1', models.PositiveIntegerField(default=0)),
                ('game5_score2', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='matches.match')),
            ],
        ),
    ]
