# Generated by Django 5.1 on 2024-08-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_set_game1_score1_alter_set_game1_score2_and_more'),
        ('users', '0002_remove_user_name_alter_user_email_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.player'),
        ),
    ]
